version: '3'
services:

  web:
    build: .
    command: FLASK_APP=app.py flask run --host=0.0.0.0 --port=8000  --cert=adhoc
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
